//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataComponentLib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public short ODId { get; set; }
        public short OrderId { get; set; }
        public short BookId { get; set; }
    
        public virtual BookTable BookTable { get; set; }
        public virtual OrderTable OrderTable { get; set; }
    }
}
