//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataComponentLib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VendorTable()
        {
            this.BookTables = new HashSet<BookTable>();
        }
    
        public short VendorId { get; set; }
        public string VendorName { get; set; }
        public string VendorEmailId { get; set; }
        public string VendorPassword { get; set; }
        public string VendorPhNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookTable> BookTables { get; set; }
    }
}
